name: Release Package
on:
  release:
    types: [created]
jobs:
  release-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Build Release Package
        run: ./gradlew packageDeb
      - name: Upload release artifact
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/compose/binaries/main/dmg/KLife-*.deb
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
  release-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Build Release Package
        run: ./gradlew packageDmg
      - name: Upload release artifact
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/compose/binaries/main/dmg/KLife-*.dmg
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
  release-windows:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Build Release Package
        run: ./gradlew packageMsi
      - name: Upload release artifact
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/compose/binaries/main/dmg/KLife-*.msi
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
